### PR TITLE
[Fixes #19473719] Redid organization forms

### PR DESCRIPTION
**Pull request by brvtl**
Using the organization form partial. Reordered the page

### CODE REVIEW

**Comment by glennr** [comment]
cant load admin form

**Comment by brvtl** [comment]
Sachin!!!!! :O

**Comment by glennr** [comment]
Reporters cannot edit AM profiles, so remove link to AM Edit page.

Also, fix the error message when a reporter visits the AM Edit page from

   "You must be logged out to access requested page "

to

  "You must be an administrator to access that page"

**Comment by glennr** [comment]
Reporters  should be able to edit their org name and their type. (see original Skitch notes)

**Comment by glennr** [comment]
@Peter - pls merge https://github.com/siyelo/hrt/pull/115 into your branch first.

**Comment by brvtl** [comment]
@glennr it has been done

**Pull request merged**
